version: 2.1

jobs:
  tests:
    parameters:
      python-version:
        type: string  

    docker:
      - image: circleci/python:<< parameters.python-version >>

    steps:
      - checkout
      - run:
          name: Run tests
          command: pip3 install poetry; poetry config virtualenvs.create false; poetry install; invoke test

workflows:
  pasar-tests: 
    jobs:
      - tests:
          matrix:
            parameters: 
              python-version: ["3.8", "3.9"]
